### ISSUE TITLE
拉备注选项可以增加教室为'教室未定'的课

### ISSUE THREAD

**Issue by tkmikan** [Tantalus13A98B5F/lesson2cal#10]
[这里讨论的课](https://github.com/Tantalus13A98B5F/lesson2cal/issues/6#issuecomment-417697690)相当一部分是`教室未定`

当然这个选项可能还要怎么和PEXC的组合一下

顺便羡慕一下形策已经上完的人

**Comment by Tantalus13A98B5F** [comment]
readme和ui文字还需要再更新一下
