### ISSUE TITLE
日期选择器可能有点灾难

### ISSUE THREAD

**Issue by LuminousXLB** [Tantalus13A98B5F/lesson2cal#16]
惊闻and design出了vue版本，考虑试用一下？

https://vue.ant.design/components/date-picker/

_Originally posted by @Tantalus13A98B5F in https://github.com/Tantalus13A98B5F/lesson2cal/pull/15#issuecomment-467275758_

**Comment by Tantalus13A98B5F** [comment]
其实一个很简单的办法是把ios外观改成mat……
![image](https://user-images.githubusercontent.com/13904366/64469212-aeb9f980-d160-11e9-93cd-c0a0831040b4.png)

**Comment by LuminousXLB** [comment]
Fantastic
