### ISSUE TITLE
Feature Request: 学期选择

### ISSUE THREAD

**Issue by tkmikan** [Tantalus13A98B5F/lesson2cal#18]
今天想拉秋季学期的课表，然而系统认为现在还是小学期
（顺带一提 课表为空时`this.lessonList.length === 0`）

现在获取学期码学年码是用的`xnm`、`xqm`，在那个页面里还有下学期的`xxnm`、`xxqm`，所以后端还算容易（本学期+下学期应该足够了）

但是在下前端苦手......

**Comment by Tantalus13A98B5F** [comment]
别苦手了 练练手啊（x

------------------------

九月初可能有时间做一下，希望来得及，希望code base没有大问题orz

**Comment by Tantalus13A98B5F** [comment]
嘿，现在已经切换学期了好像（
课表为空那个是什么意思，会出什么bug吗（

**Comment by tkmikan** [comment]
https://github.com/Tantalus13A98B5F/lesson2cal/blob/7f47228fb939754cb40846541e4457ce596fe427/static/index.js#L107
`lessonList`是空的，这一行会取不到

**Comment by Tantalus13A98B5F** [comment]
fixed
