### ISSUE TITLE
支持形势与政策的日期安排

### ISSUE THREAD

**Issue by xushangning** [Tantalus13A98B5F/lesson2cal#2]
目前生成的日历中每周都有形势与政策。

**Comment by Tantalus13A98B5F** [comment]
#6 这样可以吧。。（反正我现在没有形策课了 关我什么事.jpg
我在考虑可以把形策课的备注里的数字提取出来，然后就可以算具体日期了，然后按每次课分别添加事件，或者还是按周添加然后把日期写在备注里呢。。
emmmm我需要一个形策课备注的示例orz

**Comment by Tantalus13A98B5F** [comment]
看起来这会是我规模最大的一个临时项目（x
好吧我还不算什么，浏览器插件开发者应该更难过吧orz

**Comment by Tantalus13A98B5F** [comment]
done
