### ISSUE TITLE
把课程的备注信息添加到DESCRIPTION

### ISSUE THREAD

**Issue by LuminousXLB** [Tantalus13A98B5F/lesson2cal#6]

**Comment by Tantalus13A98B5F** [comment]
提取所有课程的备注信息可能会极大地延长用户的等待时间，并加大被服务器续命的可能性（
我现在的想法是让用户自己勾选配置，分为：无需备注、需要形策和体育课的特殊处理、需要所有备注三种

**Comment by LuminousXLB** [comment]
需要特殊处理的应当还有
电子电工实验中心开设的课程，比如工程实践（电类）、电子技术实验等
工程训练中心开设的课程，比如数据科学导论、工程实践等

**Comment by Tantalus13A98B5F** [comment]
所以要维护一个课程列表吗（然后看着它慢慢变长x
体育和形策的特点是，大家都要上，4个学期，做的话性价比还挺高（

**Comment by Tantalus13A98B5F** [comment]
done
